### PR TITLE
Auto merge dependabot dev dependency PRs

### PR DESCRIPTION
**Pull request by notlee**

### CODE REVIEW

**Comment by notlee** [comment]
hey @Financial-Times/accounts , we're auto-merging dev dependencies which are bumped by dependabot in working hours if tests pass: Financial-Times/origami#55

If the master brand is protected Dependabot will have to be added to the "Restrict who can push to matching branches" setting to merge (I don't have permission to add that):
https://github.com/dependabot/feedback/issues/86#issuecomment-523849759

I opened a PR on all Origami things, including those maintained by other teams. Feel free to close this PR if you would rather continue to review dev dependency bumps manually!

**Review by umbobabo — APPROVED** [review]
I like this @notlee 👍 the auto-mege approach. I think it's the only way we can maintain our huge estate healthy. I would love to see that Origami and Customer Product use the same tool (we use Renovate) but I guess this is a discussion that goes out of scope for this PR. FYI @andygout @rowanmanning

**Comment by andygout** [comment]
I spoke to my Platforms team about this and the responses were that:
- Apparently Edd Sowdon pushed back on the idea very strongly (we are trying to find his exact reasoning).
- A feeling that humans often do semantic versioning badly and our tests won't catch everything.

**Comment by notlee** [comment]
Hey @andygout sorry for not replying here. Re. bad semver we're comfortable allowing auto merge for dev dependencies only. However closing this PR as Origami maintained components have moved to Dependabot native now. Let us know if you'd like us to open a new PR for Dependabot native auto merging

**Comment by andygout** [comment]
Hi @notlee - I will raise this again with the Platforms team.

My personal opinion is that for dev dependencies only it should be fine.

Can I check if automerges will happen regardless or semver type (i.e. major, minor, patch)? In any case, if all tests are passing then should not matter.

**Comment by notlee** [comment]
Just had a closer look at our [new configuration](https://github.com/Financial-Times/o-table/pull/218/files) and we're actually now merging all dependabot PRs automatically. For Origami components thats dev deps only in practise as prod dependnecies are defined in bower.json out of dependabot's remit. We were automerging only minor and patch releases, but now any release it seems.

**Comment by andygout** [comment]
There has been some really interesting feedback from Platforms teams on this topic.

The reasons against doing this:
> it still boils down to: how confident are we in our tests, across every app: can we be absolutely sure that a passing test means a PR can be merged with zero human involvement. dev dependencies can still break things and semver doesn’t save you because versions are written by humans and humans make mistakes.
deliberately exaggerated example but something like this could happen: imagine if somebody accidentally released a patch version of `jest` that just immediately exited successfully without running the tests. the “tests” would “pass”, the PR would automerge, and suddenly half our apps don’t have tests without anybody noticing.

> Sometimes a version of a dependency works exactly as we need it and better to leave fixed rather than worry about upgrading (i.e. if it ain’t broke, don’t fix it).

> having a human involved means there’s more than zero people with the right context when something breaks.

> given we’ve got Snyk checking dependencies for known vulnerabilities and we’re already running `snyk protect` to patch things i’m not convinced we need to automerge Renovate PRs for security

> In my personal projects i dont have Renovate Bot/Greenkeeper. My general tactic is to manually update all dependencies from time to time. I do have snyk setup telling me about vulnerabilities too. I dont deem a patch version for a dev dependency important and for minor/major releases, I always check the changelog before updating. I also have Husky setup to run my tests before pushing to git.

> My main thought on this is that while we merge passing builds for dependencies there is a difference between doing that on a few repos and doing it on everything at the same time. one bad dependency shared between a lot of apps has the potential to break all of them silently.

The reasons for doing it are:
> (In the scenario of `jest` exiting without running tests) whether a human upgrading a patch version of jest would take the time to check that the tests are running at all/exactly as they should or trustingly push it through (admittedly the answer is that it is more likely than a bot checking :robot_face:).

> If a patch that fixes a security vulnerability is released, one merged automatically by RenovateBot will get in a lot quicker than a PR alone, which will likely sit unactioned for some time or even indefinitely.

The general opinion seems to be against having any auto-merging, even for dev dependencies. Are there more thoughts from @notlee @rowanmanning @umbobabo?

**Pull request closed without merging**
